"""Builds Stunt Fox: python3 build.py "Payback (Europe) (En,Fr,De,Es,It).gba" -o stuntfox.gba

The Payback ROM provides the city layout (and the cartridge logo); it is read, never copied
into this repository. Needs clang and ld.lld.

With --merge it builds Stunt Fox into Payback itself instead: the output is the player's own
Payback ROM, patched so that Payback's game runs as before but Stunt Fox draws the world
(see src/merge.c). --bps also writes that as a patch.
"""
import argparse
import os
import struct
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'src')
BUILD = os.path.join(HERE, 'build')
GEN = os.path.join(BUILD, 'gen')
sys.path.insert(0, os.path.join(HERE, 'tools'))
sys.path.insert(0, os.path.join(HERE, '..', 'payback-mod'))
import mkworld   # noqa: E402
import mkassets  # noqa: E402
import mkpal    # noqa: E402

CFLAGS = ['--target=armv4t-none-eabi', '-mcpu=arm7tdmi', '-O2', '-ffreestanding', '-fno-builtin',
          '-nostdlib', '-ffunction-sections', '-Wall', '-Wno-unused-function']
ARM_FILES = {'render.c', 'citydraw.c', 'fx.c', 'physics.c', 'model.c'}  # hot code: ARM, IWRAM


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit('failed: ' + ' '.join(cmd))
    if r.stderr.strip():
        sys.stderr.write(r.stderr)


def build(payback, out):
    os.makedirs(GEN, exist_ok=True)
    rom = open(payback, 'rb').read()
    data, stats = mkworld.build(rom)
    open(os.path.join(GEN, 'world.bin'), 'wb').write(data)
    mkassets.main(os.path.join(GEN, 'tables.c'))
    objs = []
    sources = [os.path.join(SRC, f) for f in sorted(os.listdir(SRC))
               if f.endswith(('.c', '.s')) and f not in MERGE_ONLY]
    sources.append(os.path.join(GEN, 'tables.c'))
    for src in sources:
        name = os.path.basename(src)
        obj = os.path.join(BUILD, name + ('.iw.o' if name in ARM_FILES else '.o'))
        if src.endswith('.s'):
            run(['clang', '--target=armv4t-none-eabi', '-mcpu=arm7tdmi', '-c', src, '-o', obj,
                 '-Wa,-I' + GEN])
        else:
            mode = '-marm' if os.path.basename(src) in ARM_FILES else '-mthumb'
            run(['clang'] + CFLAGS + [mode, '-I' + SRC, '-c', src, '-o', obj])
        objs.append(obj)
    elf = os.path.join(BUILD, 'stuntfox.elf')
    run(['ld.lld', '-T', os.path.join(SRC, 'gba.ld'), '--gc-sections', '-e', '_start', '-o', elf] + objs)
    run(['llvm-objcopy', '-O', 'binary', elf, out])
    img = bytearray(open(out, 'rb').read())
    img[4:0xa0] = rom[4:0xa0]                     # logo from the player's own cartridge
    img[0xa0:0xac] = b'STUNT FOX\0\0\0'
    img[0xac:0xb0] = b'BSFE'
    img[0xb0:0xb2] = b'01'
    img[0xb2] = 0x96
    img[0xb3:0xbd] = bytes(10)
    img[0xbd] = (-sum(img[0xa0:0xbd]) - 0x19) & 0xff
    while len(img) % 4:
        img.append(0)
    open(out, 'wb').write(img)
    return stats, len(img)


# --merge: Stunt Fox inside Payback
MERGE_ONLY = {'merge.c', 'keyhook.s', 'traffic.c', 'tex.c', 'texrun.s', 'draw2d.c', 'spacegame.c'}
MERGE_SKIP = {'main.c', 'hud.c', 'crt0.s'}
MERGE_CALLS = (0x080177fa, 0x08017692)        # Payback's two calls to its world renderer
MERGE_RENDERER = 0x0800adac
MERGE_KEYS = 0x0800e9a8                       # Payback's call to its keypad reader
MERGE_READER = 0x08072f68
MERGE_FADE = 0x0806c82c                       # Payback's palette fade, called from 23 places
MERGE_FADES = ((0x080777ec, 'sf_fade_add', 3),   # its other fades: + a level (toward white) ...
               (0x080779bc, 'sf_fade_mul', 6),   # ... and * a level (toward black), twice
               (0x08077f44, 'sf_fade_mul2', None))
MERGE_BASE = 0x081b0000                       # see src/merge.ld


def bl_target(d, site):
    """Where the Thumb bl at site goes, or None."""
    h1, h2 = struct.unpack_from('<HH', d, site - 0x08000000)
    if (h1 & 0xf800) != 0xf000 or (h2 & 0xf800) != 0xf800:
        return None
    off = (h1 & 0x7ff) << 12 | (h2 & 0x7ff) << 1
    off -= (1 << 23) if off & (1 << 22) else 0
    return site + 4 + off


def build_merge(payback, out, bps_out=None):
    from paybackmod.rom import PaybackRom, NEW_BASE, OLD_TABLE_START, OLD_TABLE_END
    from paybackmod import bps
    os.makedirs(GEN, exist_ok=True)
    orig = open(payback, 'rb').read()
    rom = PaybackRom(orig)                    # checks it is Payback (Europe); moves the column table
    data, stats = mkworld.build(orig, merge=True)
    open(os.path.join(GEN, 'world.bin'), 'wb').write(data)
    mkassets.main(os.path.join(GEN, 'tables.c'))
    mkpal.main(orig, os.path.join(GEN, 'pbtables.c'))
    grid = rom.grid(0)
    cells = [(i * 509 + 77) % len(grid) for i in range(32)]
    with open(os.path.join(GEN, 'merge_sig.c'), 'w') as f:
        f.write('/* generated by build.py: cells of Payback\'s city and their column pointers */\n')
        f.write('#include "../../src/gba.h"\nconst u32 merge_sig[32][2] = {\n')
        for c in cells:
            f.write('    {%d, 0x%08x},\n' % (c, rom.col_ptr(grid[c])))
        f.write('};\n')
    objs = []
    sources = [os.path.join(SRC, f) for f in sorted(os.listdir(SRC))
               if f.endswith(('.c', '.s')) and f not in MERGE_SKIP]
    sources += [os.path.join(GEN, 'tables.c'), os.path.join(GEN, 'merge_sig.c'), os.path.join(GEN, 'pbtables.c')]
    for src in sources:
        name = os.path.basename(src)
        obj = os.path.join(BUILD, 'merge', name + '.o')
        os.makedirs(os.path.dirname(obj), exist_ok=True)
        if src.endswith('.s'):
            run(['clang', '--target=armv4t-none-eabi', '-mcpu=arm7tdmi', '-c', src, '-o', obj,
                 '-Wa,-I' + GEN])
        else:
            run(['clang'] + CFLAGS + ['-mthumb', '-DMERGE', '-I' + SRC, '-c', src, '-o', obj])
        objs.append(obj)
    elf = os.path.join(BUILD, 'merge', 'stuntfox-merge.elf')
    run(['ld.lld', '-T', os.path.join(SRC, 'merge.ld'), '--gc-sections', '-e', 'sf_frame', '-o', elf] + objs)
    blob = os.path.join(BUILD, 'merge', 'stuntfox-merge.bin')
    run(['llvm-objcopy', '-O', 'binary', elf, blob])
    code = open(blob, 'rb').read()
    nm = subprocess.run(['llvm-nm', elf], capture_output=True, text=True).stdout
    sym = {p[2]: int(p[0], 16) for p in (l.split() for l in nm.splitlines()) if len(p) == 3}
    o = MERGE_BASE - 0x08000000
    assert OLD_TABLE_START <= o and o + len(code) <= OLD_TABLE_END, 'Stunt Fox does not fit'
    rom.d[o:o + len(code)] = code

    def redirect(site, old, new):
        a = site - 0x08000000
        assert bl_target(rom.d, site) == old, 'expected a call to %x at %x' % (old, site)
        off = (new & ~1) - (site + 4)
        struct.pack_into('<HH', rom.d, a, 0xf000 | ((off >> 12) & 0x7ff), 0xf800 | ((off >> 1) & 0x7ff))
    for site in MERGE_CALLS:
        redirect(site, MERGE_RENDERER, sym['sf_frame'])
    redirect(MERGE_KEYS, MERGE_READER, sym['sf_keyhook'])
    fades = [a for a in range(0x08000000, 0x08100000, 2) if bl_target(rom.d, a) == MERGE_FADE]
    assert len(fades) == 23, 'expected 23 calls to the palette fade, found %d' % len(fades)
    for site in fades:
        redirect(site, MERGE_FADE, sym['sf_fade'])
    for fn, hook, count in MERGE_FADES:        # (so none of them can flash the screen white)
        sites = [a for a in range(0x08000000, 0x08100000, 2) if bl_target(rom.d, a) == fn]
        assert count is None or len(sites) == count, 'expected %d calls to %x, found %d' % (count, fn, len(sites))
        for site in sites:
            redirect(site, fn, sym[hook])
    img = rom.data()
    open(out, 'wb').write(img)
    if bps_out:
        moves = [(NEW_BASE, OLD_TABLE_START, OLD_TABLE_END - OLD_TABLE_START)]
        patch = bps.encode(orig, img, moves)
        assert bps.apply(orig, patch) == img
        open(bps_out, 'wb').write(patch)
    return stats, len(code)


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('payback')
    ap.add_argument('-o', '--out', default='stuntfox.gba')
    ap.add_argument('--merge', action='store_true', help='build Stunt Fox into Payback itself')
    ap.add_argument('--bps', help='with --merge: also write a BPS patch for the Payback ROM')
    a = ap.parse_args()
    if a.merge:
        stats, size = build_merge(a.payback, a.out, a.bps)
        print('wrote %s (Payback with Stunt Fox, %d KiB of code and data), world %s' % (a.out, size // 1024, stats))
    else:
        stats, size = build(a.payback, a.out)
        print('wrote %s (%d KiB), world %s' % (a.out, size // 1024, stats))
